import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // scroll-smooth: 앵커 링크(#about 등) 이동 시 부드럽게 스크롤되도록 설정
      className={`${geistSans.variable} ${geistMono.variable} h-full scroll-smooth antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Navbar />
        {/* pt-16: Navbar의 높이(h-16)만큼 여백을 주어 콘텐츠가 가려지지 않도록 함 */}
        <div className="flex flex-1 flex-col pt-16">{children}</div>
      </body>
    </html>
  );
}
